blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/pegasusheavy/leaven/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Documentation
    url: https://leaven.dev
    about: Read the documentation
  - name: ðŸ’¡ Stack Overflow
    url: https://stackoverflow.com/questions/tagged/leaven-graphql
    about: Ask questions on Stack Overflow
